spring.application.name=rajminesvts

server.servlet.context-path=/api
server.port=8089

# ===============================
# = DataSource Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/rajmines_vts
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / Hibernate Configuration
# ===============================
# MySQL 8 dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Automatically create/update tables (use 'validate' or 'none' in production)
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console
spring.jpa.show-sql=true

# Format SQL output
spring.jpa.properties.hibernate.format_sql=true

# Use JDBC batch updates for performance
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


spring.main.allow-bean-definition-overriding=true

# ===============================
# = Connection Pool (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# Designated place for uploading
upload.dir=D:/uploads/rajminesvts/

jwt.secret=KsGRp1wju83gmza1uWD3vHVXjG/R7dZqK+N4zfuCNUI=
jwt.expiration=1800000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB